name: CI

on:
  push:
    branches: 
      - 'main'
      - 'dev'
      - 'staging'
  pull_request:
    branches: 
      - 'main'
      - 'dev'
      - 'staging'

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up JDK and Gradle
        uses: gradle/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build and Test
        run: |
          ./gradlew build
          ./gradlew spotlessApply
          ./gradlew test

  dependency-submission:
    name: Generate and Submit Dependency Graph
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up JDK and Gradle
        uses: gradle/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Generate and submit dependency graph
        uses: gradle/dependency-submission@v3

